package org.example.demo1.controllers;

import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import org.example.demo1.models.Zone;
import org.example.demo1.services.ZoneService;

public class AddZoneController {
    @FXML
    private TextField locationField;

    private ZoneService zoneService = new ZoneService();

    // Handles the "Add Zone" button click
    @FXML
    private void handleAddZone() {
        try {
            // Get the location from the input
            String location = locationField.getText().trim();

            // Check if location is not empty
            if (location.isEmpty()) {
                showAlert(AlertType.ERROR, "Error", "Location cannot be empty.");
                return;
            }

            // Create a new Zone object (ID will be auto-generated by the database)
            Zone zone = new Zone(location);

            // Add the zone using the service
            zoneService.addZone(zone);

            // Show success message
            showAlert(AlertType.INFORMATION, "Success", "Zone added successfully!");

            // Clear the form field
            locationField.clear();
        } catch (Exception e) {
            // Handle unexpected errors
            showAlert(AlertType.ERROR, "Error", "An error occurred while adding the zone.");
        }
    }

    // Utility method to show alerts
    private void showAlert(AlertType type, String title, String message) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}
